### ISSUE TITLE
CoreShop 2.0.4 dependency breaks ElasticSearchWorker - services.yaml argument missing 

### ISSUE THREAD

**Issue by FabianHippmann** [DivanteLtd/coreshop-vsbridge#20]
We just installed the coreshop-vsbridge plugin on a fresh system of pimcore + coreshop (dev-master).

After the installation the following error occurs: 

```
Type error: Too few arguments to function CoreShop\Bundle\IndexBundle\Worker\AbstractWorker::__construct(), 5 passed in /var/www/html/vendor/divante-ltd/coreshop-vsbridge/src/CoreShop2VueStorefrontBundle/Worker/ElasticSearchWorker.php on line 53 and exactly 6 expected
```

In the services.yaml there are only 5 arguments specified:

```
CoreShop2VueStorefrontBundle\Worker\ElasticSearchWorker:
        arguments:
            - '@coreshop.registry.index.extensions'
            - '@coreshop.registry.index.getter'
            - '@coreshop.registry.index.interpreter'
            - '@coreshop.index.filter_group_helper'
            - '@coreshop.index.condition.renderer'
        shared: false
        calls:
            - { method: setLogger, arguments: ['@logger'] }
        tags:
            - { name: coreshop.index.worker, type: elasticsearch, form-type: CoreShop2VueStorefrontBundle\Worker\Type\ElasticSearchWorkerType }
```

this PR from coreshop added the 6th argument without a default - 

https://github.com/coreshop/CoreShop/pull/856 

I will also open a PR with instructions for the installation & outlining the requirement for "coreshop/core-shop:2.0.x-dev"

---
**With coreshop/core-shop:2.0.1- the bridge works perfectly**
